version: "3.7"

services:
    mailhog:
        image: mailhog/mailhog
        logging:
            driver: "none"
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - web-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8081:80
        links:
            - mysql
        environment:
            - PMA_ARBITRARY=1
        networks:
            - web-network
    mysql:
        image: mysql:8.0
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_USER: demo
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: seminar-laravel
        networks:
            - web-network

    web:
        tty: true
        stdin_open: true
        build: .
        environment:
            APP_DEBUG: "true"
            XDEBUG_MODE: coverage
            PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/vendor/bin
        volumes:
            - .:/app:cached
            - ./docker-dev/web/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./docker/supervisor/:/etc/supervisor.d/
        networks:
            - web-network
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/app
            - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web
        networks:
            - web-network
volumes:
    composer_caches:
    mysql-data:
networks:
    web-network:
        driver: bridge
